---
title: "Stepwise Correction"
author: "Jeffrey Uslan"
date: "Wednesday, July 22, 2015"
output: pdf_document
---


#Fabricate some on-off data
```{r}
len=1000
good_vec=round(runif(len,max=.75))
plot(good_vec)
```

#Give it noise
```{r}
noise=rnorm(len,-.1,.1)
noise_vec=good_vec+noise
plot(noise_vec)
```

#Introduce some "step noise"
```{r}
steps=round(rnorm(20,-1,1))
t=sapply(steps,function(x) x*rep(1,50))
steps_10=NULL
for(i in 1:ncol(t)) steps_10=c(steps_10,t[,i])
step_noise=noise_vec+steps_10
plot(step_noise)
```

#Try to fix using moving median
```{r}
filter_window=5
filt=runmed((step_noise),filter_window)

plot(filt)
title("Note the averaging issue between steps")
unstep_noise=step_noise-filt
plot(unstep_noise,type="p")
title("Attempted adjustments")
```

#Fit a step function fit
```{r}
df=data.frame(x=1:len,y=step_noise)
fit=lm(df$y~0+cut(df$x,20))

step_fit=as.vector((coef(summary(fit))[,1]))
t=sapply(step_fit,function(x) x*rep(1,50))
steps_10=NULL
for(i in 1:ncol(t)) steps_10=c(steps_10,t[,i])
plot(steps_10)
unstep_noise_cut=step_noise-steps_10
plot(unstep_noise_cut)
title("Much better")
```


```{r}
par(mfrow=c(3,1))
plot(noise_vec)
plot(unstep_noise,type="p")
plot(unstep_noise_cut)
```